INSERT INTO "himpunan" ("namaHimpunan", "singkatanHimpunan", "linkFoto", "createdAt", "updatedAt")
  VALUES
    ('Himpunan Mahasiswa Meteorologi', 'HMME "ATMOSPHAIRA"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FITB-HMME-300x294.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Oseanografi', 'HMO "TRITON"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FITB-HMO-_TRITON_-ITB-268x300.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Teknik Geologi', 'HMTG "GEA"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FITB-HMTG-_GEA_-ITB-300x259.png', NOW(), NOW()),
    ('Ikatan Mahasiswa Geodesi', 'IMG', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FITB-IMG-ITB.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Fisika', 'HIMAFI', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FMIPA-HIMAFI-ITB-300x300.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Astronomi', 'HIMASTRON', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FMIPA-HIMASTRON-ITB-300x300.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Matematika', 'HIMATIKA', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FMIPA-HIMATIKA-ITB-300x260.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Kimia', 'HMK "AMISCA"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FMIPA-HMK-_AMISCA_-ITB-300x300.png', NOW(), NOW()),
    ('Ikatan Mahasiswa Desain Interior', 'IMDI', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FSRD-IMDI-ITB-300x300.jpg', NOW(), NOW()),
    ('Keluarga Mahasiswa Desain Produk', 'INDDES', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FSRD-INDDES-ITB-254x300.jpg', NOW(), NOW()),
    ('Ikatan Pemuda Pemudi Desain Grafis', 'IPPDIG', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FSRD-IPPDIG.jpg', NOW(), NOW()),
    ('Himpunan Mahasiswa Kriya', 'TERIKAT', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FSRD-terikat-ITB-300x300.jpg', NOW(), NOW()),
    ('Visual Art Student Aggregate', 'VASA', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FSRD-VASA-ITB-300x300.jpg', NOW(), NOW()),
    ('Himpunan Mahasiswa Teknik Kimia', 'HIMATEK', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTI-HIMATEK-ITB-300x203.jpg', NOW(), NOW()),
    ('Himpunan Mahasiswa Fisika Teknik', 'HMFT', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTI-HMFT-ITB-300x276.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Teknik Pangan', 'HMPG', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTI-HMPG-ITB-300x300.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Teknik Bioenergi dan Kemurgi', 'HMTB', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTI-HMTB-ITB-300x297.png', NOW(), NOW()),
    ('Keluarga Mahasiswa Teknik Industri', 'MTI', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTI-MTI-ITB-298x300.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Mesin', 'HMM', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTMD-HMM-ITB-300x292.png', NOW(), NOW()),
    ('Keluarga Mahasiswa Teknik Penerbangan', 'KMPN  "OTTO LILIENTHAL"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTMD-KMPN-ITB-300x247.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Teknik Material', 'MTM', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTMD-MTM-ITB-300x300.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Sumber Daya Air', 'HIMASDA', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTSL-HIMASDA-ITB-300x300.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Sipil', 'HMS', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTSL-HMS-ITB.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Teknik Lingkungan', 'HMTL', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTSL-HMTL-ITB-228x300.jpg', NOW(), NOW()),
    ('Keluarga Mahasiswa Infrastruktur Lingkungan', 'KMIL', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTSL-KMIL-ITB-300x300.jpg', NOW(), NOW()),
    ('Keluarga Mahasiswa Teknik Kelautan', 'KMKL', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTSL-KMKL-ITB-300x290.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Teknik Geofisika', 'HIMATG "TERRA"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTTM-HIMATG-_TERRA_-ITB-300x213.jpg', NOW(), NOW()),
    ('Himpunan Mahasiswa Tambang', 'HMT', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTTM-HMT-ITB-267x300.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Teknik Perminyakan', 'HMTM "PATRA"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTTM-HMTM-_PATRA_-ITB-300x300.png', NOW(), NOW()),
    ('Ikatan Mahasiswa Teknik Metalurgi', 'IMMG', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/FTTM-IMMG-300x300.jpg', NOW(), NOW()),
    ('Himpunan Mahasiswa Perencanaan Wilayah dan Kota Pangripta Loka', 'HMP "PANGRIPTA LOKA"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/SAPPK-HMP-PL-ITB-300x291.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Perencanaan Wilayah dan Kota Pangripta Loka Komisariat', 'HMP "PANGRIPTA LOKA" Komisariat', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/SAPPK-HMP-PL-ITB-300x291.png', NOW(), NOW()),
    ('Ikatan Mahasiswa Arsitektur Gunadharma', 'IMA-G', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/SAPPK-IMA-G-ITB-243x300.png', NOW(), NOW()),
    ('Keluarga Mahasiswa Manajemen', 'KMM', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/SBM-KMM-ITB-150x150.jpg', NOW(), NOW()),
    ('Ikatan Mahasiswa Kewirausahaan', 'IMK "Artha"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/SBM-IMK-_ARTHA_-ITB-300x300.jpg', NOW(), NOW()),
    ('Himpunan Mahasiswa Farmasi', 'HMF "ARS PRAEPARANDI"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/SF-HMF-300x295.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Rekayasa Pertanian', 'HIMAREKTA "AGRAPANA"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/SITHR-HIMAREKTA-300x300.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Rekayasa Kehutanan', 'HMH "SELVA"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/SITHR-HMH-_Selva_-ITB-300x300.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Rekayasa Hayati', 'HMRH', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/SITHR-HMRH-300x297.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Teknologi Pascapanen', 'HMPP "VADRA"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/SITHR-HMPP-_VADRA_-ITB-232x300.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Mikrobiologi', 'HIMAMIKRO "ARCHAEA"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/SITHS-HIMAMIKRO-ITB-300x300.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Biologi', 'NYMPHAEA', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/SITHS-HIMABIO-_Nymphaea_-ITB-300x300.jpg', NOW(), NOW()),
    ('Ikatan Mahasiswa Telekomunikasi', 'IMT "SIGNUM"', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/STEI-IMT-300x300.png', NOW(), NOW()),
    ('Himpunan Mahasiswa Elektroteknik', 'HME', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/STEI-HME-ITB-255x300.jpg', NOW(), NOW()),
    ('Himpunan Mahasiswa Informatika', 'HMIF', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/09/STEI-HMIF-ITB-300x200.png', NOW(), NOW()),
    ('Fakultas Ilmu dan Teknologi Kebumian', 'FITB', 'https://lh5.googleusercontent.com/NFqrfvYZAreqekaVwDWinb4IPEF0uxKSJbbZVK6GdKNPUyvI908A7vkp4cJlvTswF-UTcDgPjFSDUo9_UJDM=w1920-h950-rw', NOW(), NOW()),
    ('Fakultas Matematika dan Ilmu Pengetahuan Alam', 'FMIPA', 'https://lh6.googleusercontent.com/-jTS5ZpHB9M_9ua7iAfWgQDfsANRcTay9vI6wttVsYUjr-PEtn8mUxSkxh-NzJMyvMUy5ctahH0LqFUh6uuq=w1920-h950-rw', NOW(), NOW()),
    ('Fakultas Seni Rupa dan Desain', 'FSRD', 'https://lh3.googleusercontent.com/981GN-sELD6FNVvilXUmKlbKQinwR8a5bzN2PMlDwMD5I5KgN3gifWCLE9shQNUVVHdrYGgdzFW2a-LaVnOT=w1920-h950-rw', NOW(), NOW()),
    ('Fakultas Teknologi Industri', 'FTI', 'https://lh3.googleusercontent.com/RdROS3Ngijm56SyAeULXn8Mq_q7GXuSZczQmUdpF3gLREkgref7oABsasnMMpn2bJDfMpSGmyijHO2y0GJ2N=w1920-h950-rw', NOW(), NOW()),
    ('Fakultas Teknik Mesin dan Dirgantara', 'FTMD', 'https://km.itb.ac.id/wp/wp-content/uploads/2020/10/FTMD-20-300x300.jpg', NOW(), NOW()),
    ('Fakultas Teknik Sipil dan Lingkungan', 'FTSL', 'https://lh4.googleusercontent.com/HoF1RwtS2r-kMJHPuuygIOJXnZnftaaaZ6e6Z2W2oXW5PeeBLELgfZeU5mTm-RrGgQMbznBrdOZwjocFpDz0=w1920-h950-rw', NOW(), NOW()),
    ('Fakultas Teknik Pertambangan dan Perminyakan', 'FTTM', 'https://lh5.googleusercontent.com/KrxjoL9s6ye7ZE89te8gLb5_42mHokmMdy7YPwVWQ6LInLC5oDoW9Jjqy4HfJCzsUoC5DdEmqzoaP7WvVX0K=w1920-h950-rw', NOW(), NOW()),
    ('Sekolah Arsitektur, Perencanaan dan Pengembangan Kebijakan', 'SAPPK', 'https://lh3.googleusercontent.com/na2aTiA63LG4bhpgjO1Uj_ckB7gC1ZQ0LMII1PiYItUOyankDsLg8vnwVOYCnizehuEUl-1YpjeaT6ACxvxi=w1920-h950-rw', NOW(), NOW()),
    ('Sekolah Bisnis dan Manajemen', 'SBM', 'https://lh5.googleusercontent.com/RAR7RXFS9a3Q32XrXEe2TBeoiq5YGzb03fC2HiT0T1L_fYl3-Q_Ug0opCIbXI3wDb2U-gc4i5ODKtB3RJjn9=w1920-h950-rw', NOW(), NOW()),
    ('Sekolah Farmasi', 'SF', 'https://lh5.googleusercontent.com/W0C5qqTtjSVo-NUqVy01NSyrgGAZwJdTkZhd-_bU4OAmVORSR03v9Ga88SLKnyymSIM4zawR06UcTrpJnNYs=w1920-h950-rw', NOW(), NOW()),
    ('Sekolah Ilmu Teknologi Hayati – Rekayasa', 'SITH-R', 'https://lh6.googleusercontent.com/sGGAXRZcmmJtKg2uU5iskLkswS5VTCtJRcm29Hk6G3LfJPlUhI9OBXXycdzqNbo0w2oa-4It2Bzy77ubrnoQ=w1920-h950-rw', NOW(), NOW()),
    ('Sekolah Ilmu Teknologi Hayati – Sains', 'SITH-S', 'https://lh4.googleusercontent.com/n3UYGF8BLYIFAybxu_jltHzdBWMBRrPRUpRGz9Sru7x5FhXEq_4Z9CLZaszP_yQChgarlqP_ogHk7wUe0hE7=w1920-h950-rw', NOW(), NOW()),
    ('Sekolah Teknik Elektro dan Informatika', 'STEI', 'https://lh5.googleusercontent.com/PePVIHqthQmT_ijZrI4KorAH49iYa8NIt5rsSEmFTR08RC93dDXVhtkv-_1qRi8q6pD5eoxXPFvbkH0ComCb=w1920-h950-rw', NOW(), NOW());
