INSERT INTO "jurusan" ("idJurusan", "namaJurusan", "idHimpunan", "createdAt", "updatedAt")
  VALUES
    ('101', 'Matematika', '7', NOW(), NOW()),
    ('102', 'Fisika', '5', NOW(), NOW()),
    ('103', 'Astronomi', '6', NOW(), NOW()),
    ('104', 'Mikrobiologi', '41', NOW(), NOW()),
    ('105', 'Kimia', '8', NOW(), NOW()),
    ('106', 'Biologi', '42', NOW(), NOW()),
    ('107', 'Sains dan Teknologi Farmasi', '36', NOW(), NOW()),
    ('108', 'Aktuaria', '7', NOW(), NOW()),
    ('112', 'Rekayasa Hayati', '39', NOW(), NOW()),
    ('114', 'Rekayasa Pertanian', '37', NOW(), NOW()),
    ('115', 'Rekayasa Kehutanan', '38', NOW(), NOW()),
    ('116', 'Farmasi Klinik dan Komunitas', '36', NOW(), NOW()),
    ('119', 'Teknologi Pasca Panen', '40', NOW(), NOW()),
    ('120', 'Teknik Geologi', '3', NOW(), NOW()),
    ('121', 'Teknik Pertambangan', '28', NOW(), NOW()),
    ('122', 'Teknik Perminyakan', '29', NOW(), NOW()),
    ('123', 'Teknik Geofisika', '27', NOW(), NOW()),
    ('125', 'Teknik Metalurgi', '30', NOW(), NOW()),
    ('128', 'Meteorologi', '1', NOW(), NOW()),
    ('129', 'Oseanografi', '2', NOW(), NOW()),
    ('130', 'Teknik Kimia', '14', NOW(), NOW()),
    ('131', 'Teknik Mesin', '19', NOW(), NOW()),
    ('132', 'Teknik Elektro', '44', NOW(), NOW()),
    ('133', 'Teknik Fisika', '15', NOW(), NOW()),
    ('134', 'Teknik Industri', '18', NOW(), NOW()),
    ('135', 'Teknik Informatika', '45', NOW(), NOW()),
    ('136', 'Teknik Dirgantara', '20', NOW(), NOW()),
    ('137', 'Teknik Material', '21', NOW(), NOW()),
    ('143', 'Teknik Pangan', '16', NOW(), NOW()),
    ('144', 'Manajemen Rekayasa', '18', NOW(), NOW()),
    ('145', 'Teknik Bioenergi dan Kemurgi', '17', NOW(), NOW()),
    ('150', 'Teknik Sipil', '23', NOW(), NOW()),
    ('151', 'Teknik Geodesi dan Geomatika', '4', NOW(), NOW()),
    ('152', 'Arsitektur', '33', NOW(), NOW()),
    ('153', 'Teknik Lingkungan', '24', NOW(), NOW()),
    ('154', 'Perencanaan Wilayah dan Kota', '31', NOW(), NOW()),
    ('155', 'Teknik Kelautan', '26', NOW(), NOW()),
    ('157', 'Rekayasa Infrastruktur Lingkungan', '25', NOW(), NOW()),
    ('158', 'Teknik dan Pengelolaan Sumber Daya Air', '22', NOW(), NOW()),
    ('170', 'Seni Rupa', '13', NOW(), NOW()),
    ('172', 'Kriya', '12', NOW(), NOW()),
    ('173', 'Desain Interior', '9', NOW(), NOW()),
    ('174', 'Desain Komunikasi Visual', '11', NOW(), NOW()),
    ('175', 'Desain Produk', '10', NOW(), NOW()),
    ('180', 'Teknik Tenaga Listrik', '44', NOW(), NOW()),
    ('181', 'Teknik Telekomunikasi', '43', NOW(), NOW()),
    ('182', 'Sistem dan Teknologi Informasi', '45', NOW(), NOW()),
    ('183', 'Teknik Biomedis', '44', NOW(), NOW()),
    ('190', 'Manajemen', '34', NOW(), NOW()),
    ('192', 'Kewirausahaan', '35', NOW(), NOW());