name: CI/CD
on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: installing modules
      run: yarn
    - name: linting
      run: yarn lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v2
    - name: Upload image to registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: paradewisudaitb/backend-wisjul21/wisjul21-be-dev
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        register: ghcr.io
        tags: "development"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Update container on server
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker-compose pull
            docker-compose up --build -d --remove-orphans